"""sync_model_drift

Revision ID: b94554138052
Revises: 0001_initial
Create Date: 2026-07-01 11:25:38.859048

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b94554138052'
down_revision: str | None = '0001_initial'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('invitations_token_key'), 'invitations', type_='unique')
    op.create_index(op.f('ix_invitations_token'), 'invitations', ['token'], unique=True)
    op.create_foreign_key(None, 'invitations', 'users', ['invited_by_id'], ['id'], ondelete='SET NULL')
    op.add_column('refresh_tokens', sa.Column('ip_address', sa.String(length=64), nullable=True))
    op.drop_constraint(op.f('refresh_tokens_token_hash_key'), 'refresh_tokens', type_='unique')
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_foreign_key(None, 'refresh_tokens', 'refresh_tokens', ['replaced_by_id'], ['id'], ondelete='SET NULL')
    op.drop_column('refresh_tokens', 'ip')
    op.alter_column('sector_countries', 'timezone',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=64),
               nullable=False)
    op.alter_column('sector_keywords', 'language',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=8),
               existing_nullable=False,
               existing_server_default=sa.text("'tr'::character varying"))
    op.drop_column('sector_keywords', 'weight')
    op.alter_column('sector_message_angles', 'language',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=8),
               existing_nullable=False,
               existing_server_default=sa.text("'tr'::character varying"))
    op.add_column('sector_target_customers', sa.Column('description', sa.Text(), nullable=True))
    op.alter_column('sector_target_customers', 'language',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=8),
               existing_nullable=False,
               existing_server_default=sa.text("'tr'::character varying"))
    op.add_column('sectors', sa.Column('product_name', sa.String(length=160), nullable=True))
    op.alter_column('sectors', 'default_language',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=8),
               existing_nullable=False,
               existing_server_default=sa.text("'tr'::character varying"))
    op.alter_column('tenants', 'name',
               existing_type=sa.VARCHAR(length=160),
               type_=sa.String(length=120),
               existing_nullable=False)
    op.alter_column('tenants', 'default_locale',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=8),
               existing_nullable=False,
               existing_server_default=sa.text("'tr'::character varying"))
    op.alter_column('tenants', 'default_timezone',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=64),
               existing_nullable=False,
               existing_server_default=sa.text("'Europe/Istanbul'::character varying"))
    op.drop_constraint(op.f('tenants_slug_key'), 'tenants', type_='unique')
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.add_column('users', sa.Column('locale', sa.String(length=8), nullable=False))
    op.add_column('users', sa.Column('timezone', sa.String(length=64), nullable=False))
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=160),
               type_=sa.String(length=120),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'full_name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=160),
               existing_nullable=True)
    op.drop_column('users', 'timezone')
    op.drop_column('users', 'locale')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.create_unique_constraint(op.f('tenants_slug_key'), 'tenants', ['slug'], postgresql_nulls_not_distinct=False)
    op.alter_column('tenants', 'default_timezone',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=40),
               existing_nullable=False,
               existing_server_default=sa.text("'Europe/Istanbul'::character varying"))
    op.alter_column('tenants', 'default_locale',
               existing_type=sa.String(length=8),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False,
               existing_server_default=sa.text("'tr'::character varying"))
    op.alter_column('tenants', 'name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=160),
               existing_nullable=False)
    op.alter_column('sectors', 'default_language',
               existing_type=sa.String(length=8),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False,
               existing_server_default=sa.text("'tr'::character varying"))
    op.drop_column('sectors', 'product_name')
    op.alter_column('sector_target_customers', 'language',
               existing_type=sa.String(length=8),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False,
               existing_server_default=sa.text("'tr'::character varying"))
    op.drop_column('sector_target_customers', 'description')
    op.alter_column('sector_message_angles', 'language',
               existing_type=sa.String(length=8),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False,
               existing_server_default=sa.text("'tr'::character varying"))
    op.add_column('sector_keywords', sa.Column('weight', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
    op.alter_column('sector_keywords', 'language',
               existing_type=sa.String(length=8),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False,
               existing_server_default=sa.text("'tr'::character varying"))
    op.alter_column('sector_countries', 'timezone',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=40),
               nullable=True)
    op.add_column('refresh_tokens', sa.Column('ip', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.create_unique_constraint(op.f('refresh_tokens_token_hash_key'), 'refresh_tokens', ['token_hash'], postgresql_nulls_not_distinct=False)
    op.drop_column('refresh_tokens', 'ip_address')
    op.drop_constraint(None, 'invitations', type_='foreignkey')
    op.drop_index(op.f('ix_invitations_token'), table_name='invitations')
    op.create_unique_constraint(op.f('invitations_token_key'), 'invitations', ['token'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
